apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-consumerbeam
  namespace: my-beam-project
  labels:
    app: beam-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-python
  template:
    metadata:
      labels:
        app: beam-python
    spec:
      containers:
        - name: beam-python
          image: arinannp/python-kafka-consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "debezium"
            - name: POSTGRES_PASSWORD
              value: "debezium"
            - name: POSTGRES_DB
              value: "debezium_db"
            - name: POSTGRES_HOST
              value: "postgres-np-svc.my-postgres-project:5432"
            - name: TABLE_DEST
              value: "person_identity_captured"
            - name: BOOTSTRAP_SERVER
              value: my-cluster-kafka-kafka-external-bootstrap.my-kafka-project:9094
            - name: TOPIC_NAME
              value: debeziumconn.public.person_identity
      restartPolicy: Always