apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-cluster-kafkaconnect-dbz
  namespace: my-kafka-project
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.2.3
  replicas: 1
  image: arinannp/strimzi-dbz-postgres-connector:latest
  bootstrapServers: my-cluster-kafka-kafka-bootstrap:9092
  config:
    group.id: dbz-connect-cluster-1
    offset.storage.topic: dbz-connect-cluster-offsets-1
    config.storage.topic: dbz-connect-cluster-configs-1
    status.storage.topic: dbz-connect-cluster-status-1
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1